### ISSUE TITLE
Twig BUG with ! Symbol

### ISSUE THREAD

**Issue by evwerkz** [OFFLINE-GmbH/oc-boxes-support#121]
Very strange, but if I add this symbol >>> ! <<<< to default, I become this error:

![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/49227960/fe07d7d2-ac8c-4509-9027-5e095f232c2a)

My code:
`
form:
    fields:
        title:
            label: Title
            type: text
            default: 'News und Angebote zu Inklusion - seid dabei!'
`

![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/49227960/4d649e90-f924-4fef-9ec8-38ff8a390784)

Testing with October 3.6.*
Twig: 3.8.0 & 3.9.3

**Comment by tobias-kuendig** [comment]
Are you using separate yaml and htm files or is it all in a single file? This feature is highly experimental and it is very likely, that an issue like this can occur.

**Comment by evwerkz** [comment]
> Are you using separate yaml and htm files or is it all in a single file? This feature is highly experimental and it is very likely, that an issue like this can occur.

in same file.

**Comment by tobias-kuendig** [comment]
@evwerkz since this is an experimental feature this is unfortunately a wontfix issue. 

Twig will always parse the yaml config since it is in the content of the partial file. In general it is just interpreted as text and therefore works without an issue. I don't know right away why the `!` is resulting in this problem but it is probably not solvable anyways. We cannot simply catch and ignore that exception since it is desired that Twig warns us about syntax errors.

In this case, I suggest you remove the `!` from the example data or you split the partial up into two separate files.
