### ISSUE TITLE
BOXES_RENDER_SCAFFOLDING=false ignored in backend

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#137]
**Describe the bug**

When you set BOXES_RENDER_SCAFFOLDING=false in your .env file, the extra added parent div is correctly removed on frontend, but not on backend.

**Boxes Version**
v3.6.15

**Comment by tobias-kuendig** [comment]
@PubliAlex thank you for this report. Unfortunately, we cannot completely remove the scaffolding in the backend since the editor relies on the meta data stored on the DOM node.

You can define a rule like this to "disable" the scaffolding node in CSS. This way it won't mess with your `grid/flex` containers.

```css
.oc-box {
    display: contents;
}
```
