### ISSUE TITLE
Fileupload infos are not saved

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#14]
**Describe the bug**
Meta informations you set on a file uploaded with fileupload widget are not savec

**To Reproduce**
1. Create a box with fileupload widget
2. Upload a media, add a Title and a Description to that media
3. Save your box
4. Edit your box again and open your media popup, title and description are empty

**Code**
Here is a quick box example config

    handle: slider
    section: Médias
    name: Slider d'images
    icon: 
    form:
        tabs:
            fields:
                images:
                    label: Images
                    type: fileupload
                    mode: image
                    tab: Général

**Screenshots**
![image](https://user-images.githubusercontent.com/55833027/190352552-6507a002-1d83-403c-b070-a0dffed0ef05.png)

**Comment by tobias-kuendig** [comment]
Thank you for this report! This is actually a known issue that we try to resolve. The information should be persisted if you add it to an already existing file (not when initially uploading it).

**Comment by tobias-kuendig** [comment]
This problem is tricky or rather next to impossible to solve because we are working with a double deferred binding (unsaved box + unsaved file attachment to that box).

The latest version displays an error and tells the user to save the Box first. This is not ideal, but at least the user knows that the changes are not saved.
