### ISSUE TITLE
Display double Delete Confirm Box

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#172]
**Describe the bug**
when deleting a box, it displays 2 delete confirm box.
The 1st works fine
then the 2nd, which shouldnt be here, display an error after confirmation.

**Boxes Version**
v3.x.y

**Screenshots**

![image](https://github.com/user-attachments/assets/553d3f24-77e8-455a-932f-389c6b811f5b)

**Comment by tobias-kuendig** [comment]
Can you check that your `{% scripts %}` are only included once in your theme?

Check your network console, the `plugins/offline/boxes/assets/js/offline.boxes.editor.js` file should only appear once (when working in the backend editor), if it appears multiple times, check where it is included.

The double box probably is because the event listener is attached to the button twice.

**Comment by chrisvidal** [comment]
you are right, somehow my theme is using 2 times `{% scripts %}`. 
thanks @tobias-kuendig
