### ISSUE TITLE
Unable to upload svg image files 

### ISSUE THREAD

**Issue by AbdulSamaddestring** [OFFLINE-GmbH/oc-boxes-support#60]
**Describe the bug**
I'm trying to find a way using which i can upload svg type image files 

**Boxes Version**
v2.2.9

**To Reproduce**
1. Go to content and select a box with upload image option
2. try to upload svg files it will show as disabled.

**Comment by tobias-kuendig** [comment]
Thank you for this report!

Boxes does not block any uploads. This problem is very likely caused by your October CMS configuration. SVG uploads are blocked by default, see: https://docs.octobercms.com/3.x/cms/media/introduction.html#svg-uploads-are-disabled-by-default

Let me know if the configuration change does not solve the issue for you.

**Comment by AbdulSamaddestring** [comment]
@tobias-kuendig I have added the svg in media config. but still not allowing.

**Comment by AbdulSamaddestring** [comment]
@tobias-kuendig even i tested by uploading to media menu and svg uploads there.

**Comment by tobias-kuendig** [comment]
Are you able to upload a SVG file in the media section directly? Are you trying to use a `type: fileupload` in Boxes? If so, do you have any `fileTypes` or `mimeTypes` option set on that field?

**Comment by AbdulSamaddestring** [comment]
Nope.

**Comment by AbdulSamaddestring** [comment]
@tobias-kuendig here's the form fields for image

        image:
            label: Image
            type: fileupload

**Comment by AbdulSamaddestring** [comment]
> Are you able to upload a SVG file in the media section directly? 
Yes

**Comment by tobias-kuendig** [comment]
> 2. try to upload svg files it will show as disabled.

Can you tell me more details about this? Where/what does show as disabled? Do you see any error? Could you share a screenshot?

**Comment by AbdulSamaddestring** [comment]
@tobias-kuendig following is the screenshot. can't select svg image

https://drive.google.com/file/d/1LJVvWJNntjA1TH0TlxhMgKzjznUiCgHG/view?usp=sharing

**Comment by AbdulSamaddestring** [comment]
@patrick-durrer @tobias-kuendig @Andi-Moser any update on it

**Comment by tobias-kuendig** [comment]
This is most certainly not a problem with the Boxes plugin as we don't restrict, what you can upload. 

The screenshot indicates, that October is blocking SVG files from being uploaded. This either happens because SVGs are not allowed to be uploaded globally or you don't allow svg files in the `fileTypes` option of your `fileupload` widget.

Please try the following:

Create a custom plugin (or edit an existing one). Add your fileupload to any `fields.yaml` in that plugin and see if you can upload the SVG file there.

**Comment by tobias-kuendig** [comment]
Another user has reported this issue. I have added an issue to our internal tracker to try and reproduce this problem.

#81

**Comment by tobias-kuendig** [comment]
October does not allow SVG files for image uploads by default. To fix this issue either set the mode of the file upload explicitly to `file`:

```yaml
        image:
            type: fileupload
            mode: file            # this is important
```

or allow `svg` files as images by adding this to your `config/cms.php`:

```php
    // Allow additional file extensions to be uploaded.
    'file_definitions' => [
        'image_extensions' => [
            'jpg',
            'jpeg',
            'bmp',
            'png',
            'webp',
            'gif',
            'svg',
        ]
    ]
```
