### ISSUE TITLE
Error at install (seems to be caused by dependency with GuzzleHttp/promises)

### ISSUE THREAD

**Issue by hmsuchier** [OFFLINE-GmbH/oc-boxes-support#63]
**Describe the bug**
On both Octobercms 3.12 & 3.14 Installation fails. In php logs, I get the error 
`NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/srv/www/vendor/composer/../guzzlehttp/promises/src/functions_include.php' (include_path='.:/usr/local/lib/php') in /srv/www/vendor/composer/autoload_real.php:41
`
manually composer require guzzlehttp/promises & then reinstall seems to solve the problem though.
**Boxes Version**
v2.2.12

**To Reproduce**
1. Install the plugin

**Comment by tobias-kuendig** [comment]
Thank you for the report!

Boxes does not have any third-party dependencies other than October's library. Which means we do not require any of the guzzlehttp packages.

Do you have any other packages/plugins installed in your October installation? If so, the problem probably comes from them, rather than Boxes.

Try running the following command to see which packages require guzzlehttp/promises:

```bash
composer why guzzlehttp/promises
```

**Comment by hmsuchier** [comment]
Hi, sorry to have bothered you for no reason then. The suggested command shows that the dependency is from october itself. I think the issue can be closed!

**Comment by tobias-kuendig** [comment]
No worries! Thank you!
