### ISSUE TITLE
Improve editing experience

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-boxes-support#72]
Firstly, thank you for this awesome module that is the perfect tool for developpers to provide a tailor made interface to end user for the best editing experience with october cms.

I wonder if it can goes even further with some ideas that came to my mind by testing the tool.

- It would be great to be able to have some more permissions that would allow to remove boxes and page addition and reordering (which would remove the whole left sidebar if checked).
- It would be aweome to provide a kind of "inline" editing integration that would replace box editing form in the right sidebar, to give the feeling to have a more "direct control" on our content. It would probably represent a lot of work to create a good ux that would integrate well with all october form widgets, but it would be awesome.
- I also see that it has been request, but it's true that the integration with the october cms backend editor would be awesome. To be able to create the .yaml config files directly in the october backend.
- A last small thing I noticed : When you add a new box, it feel quite strange to not directly see the box added in the main area. I think it would be better for the UI to directly add it to the main area after clicking on the "add box" button, and then, edit it using the right panel.

Whats your opinion about these 2 ideas ? 

Best regards,

**Comment by tobias-kuendig** [comment]
@Zmove thank you for your feedback. Here are my thoughts:

> It would be great to be able to have some more permissions that would allow to remove boxes and page addition and reordering (which would remove the whole left sidebar if checked).

It is true that the permission system is currently almost non-existent. I have added a task to our internal backlog to tackle this problem sometime.

> It would be aweome to provide a kind of "inline" editing integration that would replace box editing form in the right sidebar, to give the feeling to have a more "direct control" on our content. It would probably represent a lot of work to create a good ux that would integrate well with all october form widgets, but it would be awesome.

The beauty of the current system is that we are very close to October's backend paradigms. For example, by re-using all the form widgets we automatically inherit all of the permissions, field triggers, events for extension, etc. Moving the editing "inline" means that we have to build everything from scratch and devs who implement Boxes may need to learn a new paradigm. Also, having the editing inline means that you as a dev have to add more code to your partials. Currently, everything is just plain old Twig. Having the editing inline would add more code to your partials. 

We believe that the benefits of inline editing are not worth the complexity it introduces. If you want to read a good horror story go look at what Wordpress did with their Full Page Editing transition that essentially forces devs now to write everything in React just to have the editing inline.

Never say never, but for the time being inline editing is out of the scope for Boxes.

> I also see that it has been request, but it's true that the integration with the october cms backend editor would be awesome. To be able to create the .yaml config files directly in the october backend.

We have this in the backlog. The Editor is not that easy to extend (there's no documentation). While it should in theory be possible, it might require some changes to the core. Solving this problem is time consuming, but I agree that it would be a nice addition.

> A last small thing I noticed : When you add a new box, it feel quite strange to not directly see the box added in the main area. I think it would be better for the UI to directly add it to the main area after clicking on the "add box" button, and then, edit it using the right panel.

Your feedback just motivated me to implement this. It is now a feature in Boxes v3.1! See https://docs.boxes.offline.ch/getting-started/changelog.html#version-3-1

It only renders the preview. Having it added to the page directly would work if the revision system is enabled (since you will publish the changes on demand), but the current placeholder workflow must remain active if the revision system is disabled or unavailable (in the free version). I may add logic to handle these cases in a future version.
