### ISSUE TITLE
UX improvement : Yaml editor like code editor

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#84]
Hello,

This plugin is incredible, it allow to create very configurable themes blazing fast.

However, the most time-consuming thing is having to edit the block configuration in a file other than html.

When you look at october cms core concept, they could merge configuration options, php code and markup in an unique file, separating things with the == character, and, on the backoffice, you can switch for example between markup and php using tabs in the code editor.

Could it be the same thing with boxes ? It would be soo much great to be able to configure your box and to write the markup in the same tab, just by switching between "Markup" and "Configuration" editor subtabs. 

I don't know if the october backend editor API allow that, but it would be awesome.

Best regards,

**Comment by tobias-kuendig** [comment]
Hi @PubliAlex 

Thank you for your feedback. We have actually received this wish multiple times already (see #4, #80) and I do thing this is a valuable addition. I currently have it in my backlog.

Since it requires some rather large changes in how partials are loaded (we need to look at each file that could contain Boxes code and no longer only at files with a .yaml pair), this is not a small problem to solve.

I'll update this issue once I found the time to tackle this problem.

**Comment by PubliAlex** [comment]
Lol, the post #80 is also mine, I didn't remember I already posted to ask for this, can close this one it's a duplicate, sorry
